name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies and cross compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential xorriso grub-pc-bin grub-common mtools gcc-i686-linux-gnu binutils-i686-linux-gnu

    - name: Run make
      run: make clean && make CC=i686-linux-gnu-gcc AS=i686-linux-gnu-as CFLAGS="-std=gnu99 -ffreestanding -O2 -Wall -Wextra -I include -U__linux__"
